Code Segments 1

```{r} 
# install.packages("ggplot2")
library(ggplot2)
 
 
``` 
```{r} 

 
qplot(diamonds$cut, diamonds$carat)
qplot(carat, price, data = diamonds)
``` 
```{r}
qplot(carat, price, data = diamonds, colour=clarity)
qplot(carat, price, data = diamonds, geom=c("point", "smooth"), method=lm)
 
``` 
```{r}
 
qplot(diamonds$cut, diamonds$carat)
qplot(carat, price, data = diamonds)
``` 
```{r}
qplot(carat, price, data = diamonds, colour=clarity)
qplot(carat, price, data = diamonds, geom=c("point", "smooth"), method=lm)
 
 
 ``` 
```{r}
qplot(carat, data = diamonds,   geom="histogram")
qplot(carat, data = diamonds,   geom="histogram", binwidth = 1)
``` 
```{r}
qplot(carat, data = diamonds,   geom="histogram", binwidth = 0.1)
qplot(carat, data = diamonds,   geom="histogram", binwidth = 0.01)
 
 

 
``` 
#### Using `ggplot()`
```{r} 
d <- ggplot(diamonds, aes(x=carat, y=price))
d + geom_point()
d + geom_point(aes(colour = carat))
d + geom_point(aes(colour = carat)) + scale_colour_brewer()
``` 
```{r} 
 
ggplot(diamonds) + geom_histogram(aes(x=price)) 
 ``` 
```{r}
 
p <- ggplot(diamonds, aes(x=price))
``` 
```{r}
p + geom_histogram()
p + stat_bin(geom="area")
``` 
```{r}
p + stat_bin(geom="point")
``` 
```{r}
p + stat_bin(geom="line")
 
``` 
```{r}
p + geom_histogram(aes(fill = clarity))
``` 
```{r}
p + geom_histogram(aes(y = ..density..))
``` 
```{r}
 
 
Setting vs mapping
 
 
p <- ggplot(diamonds, aes(x=carat,y=price))
 
# What will this do?
``` 
```{r}
p + geom_point(aes(colour = "green"))
p + geom_point(colour = "green")
p + geom_point(colour = colour)
 
