About the Course
===============================
The goals of this course are as follows:
- Recognize the importance of data collection, identify limitations in data collection methods, and determine how they affect the scope of inference.
- Use statistical software (R) to summarize data numerically and visually, and to perform data analysis.
- Have a conceptual understanding of the unified nature of statistical inference.
- Apply estimation and testing methods (confidence intervals and hypothesis tests) to analyze single variables and the relationship between two variables in order to understand natural phenomena and make data-based decisions.
- Model and investigate relationships between two or more variables within a regression framework.
- Interpret results correctly, effectively, and in context without relying on statistical jargon.
- Critique data-based claims and evaluate data-based decisions.
- Complete a research project that employs simple statistical inference and modeling techniques.

### Course Syllabus

Week 1: Unit 1 - Introduction to data
Week 2: Unit 2 - Probability and distributions
Weeks 3 & 4: Unit 3 - Foundations for inference + Midterm
Week 5: Unit 4 - Statistical inference for numerical variables
Week 6: Unit 5 - Statistical inference for categorical variables
Week 7: Unit 6 - Simple linear regression
Week 8: Unit 7 - Multiple linear regression
Week 9: Capstone project
Week 10: Final exam
